name: Chapter 7 Checks

on:
  push:
    branches: # <1>
      - main
defaults: # DO NOT INCLUDE
  run:
    working-directory: ./ch7
jobs:
  format-check:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x 
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Run Format Check
      run: make check-format
    - name: Vet
      run: go vet ./... # <1>
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        uses: golangci/golangci-lint-action@v2 
        with:
          working-directory: ch7
  test:
    name: Test Application
    needs: 
      - format-check
      - lint
    runs-on: ubuntu-latest # <2>
    steps:
    - name: Set up Go 1.x 
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
    - name: Check out code into the Go module directory 
      uses: actions/checkout@v2
    - name: Run Test
      run: make test # <1>
    - name: Coverage Check
      run: make coverage # <2>
    - name: Generate Report
      run: make report # <3>
    - name: Copy Files 
      run: |
           mkdir  reports
           cp cover.html reports/.

    - name: Archive # <4>
      uses: actions/upload-artifact@v2
      with:
          name: reports
          path: ch7/reports  # Do not include ch7
  build:
    name: Build App
    runs-on: ubuntu-latest #
    needs: test #<6>
    steps:
    - name: Set up Go 1.x #
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Check out code into the Go module directory #
      uses: actions/checkout@v2

    - name: Build
      run: make build #

    - name: Copy Files #
      run: |
           mkdir  artifacts
           cp api artifacts/.

    - name: Archive #
      uses: actions/upload-artifact@v2
      with:
          name: api #
          path: 5/artifacts  # Do not include ch7
  deliver:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download binary # <4>
        uses: actions/download-artifact@v2
        with:
          name: api
      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false
      - name: Upload Release Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: api
          asset_name: api
          asset_content_type: application/octet-stream
  containerize-buildpack:
    name: Build Container buildpack
    runs-on: ubuntu-latest #
    needs: test #<6>
    steps:
    - name: Check out code into the Go module directory #
      uses: actions/checkout@v2
    - name: Install Pack
      run: (curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.21.1/pack-v0.21.1-linux.tgz" | sudo tar -C /usr/local/bin/ --no-same-owner -xzv pack)
    - name: Build
      run: pack build gcr.io/${{ secrets.GCP_PROJECT_ID }}/hello-api:latest --builder gcr.io/buildpacks/builder:v1
    - name: Configure Docker
      run: gcloud auth configure-docker --quiet
    - name: Push Docker image
      run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/hello-api:latest
  deploy-container:
    name: Deploy Container buildpack
    runs-on: ubuntu-latest # 
    needs: containerize-buildpack #<6>
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:    
    - name: Deploy to CaaS
      id: deploy
      uses: google-github-actions/deploy-cloudrun@main
      with:
        service: translate
        image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/hello-api:latest
        credentials: ${{ secrets.gcp_credentials }}
    - id: test
      run: curl "${{ steps.deploy.outputs.url }}/hello"
  # deploy-function:
  #   name: Deploy FaaS
  #   runs-on: ubuntu-latest
  #   needs: test
  #   if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
  #   steps:
  #   - name: Check out code into the Go module directory # <4>
  #     uses: actions/checkout@v2
  #     with:
  #       fetch-depth: 0
  #   - name: Deploy function
  #     id: deploy
  #     uses: google-github-actions/deploy-cloud-functions@main
  #     with:
  #       name: translate
  #       entry_point: Translate
  #       runtime: go113
  #       credentials: ${{ secrets.gcp_credentials }}
  #       source_dir: ch7 # DO NOT INCLUDE
  #   - id: test
  #     run: curl "${{ steps.deploy.outputs.url }}/hello"
  # deploy-paas:
  #   name: Deploy PaaS
  #   runs-on: ubuntu-latest
  #   needs: test
  #   if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
  #   steps:
  #   - name: Check out code into the Go module directory # <4>
  #     uses: actions/checkout@v2
  #     with:
  #       fetch-depth: 0
  #   - name: Deploy App
  #     id: deploy
  #     uses: google-github-actions/deploy-appengine@main
  #     with:
  #       credentials: ${{ secrets.gcp_credentials }}
  #       working_directory: ch7 # DO NOT INCLUDE
  #   - id: test
  #     run: curl "${{ steps.deploy.outputs.url }}/translate/hello"